<form action="<?php echo $block->getFormActionUrl('sushma/index/index') ?>" method="POST">
    <label for="employee_id">Employee Id</label>
    <input type="text" name="employee_id" id="employee_id"/>
    <label for="firstName">First Name</label>
    <input id="firstName" type="text" name="first_name"/>
    <label for="lastName">Last Name</label>
    <input type="text" name="last_name" id="lastName"/>
    <label for="email_id">Email Id</label>
    <input type="email" name="email_id" id="email_id"/>
     <button type="submit">Submit</button>
</form>