<!-- <table> -->
    <!-- <tr>
        <th>Employee Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email Id</th>
    </tr> -->
    <?php
        $employees =  $block->getEmployeeDetails()->toArray();
        usort($employees, function($a, $b) {
            return strcmp($a->getEntityId(), $b->getEntityId());
        });
        // usort($employees, function($a, $b) {
        //     return strcmp($a->getEntityId(), $b->getEntityId());
        // });
        foreach ($employees as $employee) {
        // Display the employee data...
            echo $employee->getFirstName()."\t\t";
            echo $employee->getLastName()."\t\t";
            echo $employee->getEmailId()."\t\t";
            echo $employee->getAddress()."\t\t";
            echo $employee->getPhoneNumber()."<br/>";
        }
    ?>
<!-- </table> -->