<?php $params = $block->getRequest()->getParams();?> 
<?php if (array_key_exists('affiliate', $params) && $params['affiliate']):?>
    <div id="product-review-container" data-role="product-review"></div>
    <?php echo $block->getChildHtml();?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
<?php endif;?>